site_name: Mari's Tech Radar
nav:
    - All about REST APIs: all-about-rest-apis.md
    - Learnings from Spring boot: learnings-spring-boot.md
    - Learnings from Java : learnings-java.md
    - Learnings from ReactJs : learnings-react.md
theme:
  name: material
